# Generated by Django 5.0.3 on 2024-04-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0013_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
